import { json, type LoaderFunction } from "@remix-run/cloudflare";
import { cogneeGraphData } from "../data/cognee-graph";

// Returns the Cognee-generated knowledge graph from resume.html
// This graph was processed by Cognee from the resume HTML directly
// Generated by: tools/cognee_from_resume.py

export const loader: LoaderFunction = async () => {
  // Return the Cognee-processed graph directly from cognee-graph.json
  return json({
    nodes: cogneeGraphData.nodes,
    edges: cogneeGraphData.edges,
    lastUpdated: cogneeGraphData.lastUpdated,
    source: "cognee",
    cognified: true,
    nodeCount: cogneeGraphData.nodeCount,
    edgeCount: cogneeGraphData.edgeCount
  }, {
    headers: {
      "Cache-Control": "no-cache, no-store, must-revalidate",
      Pragma: "no-cache",
      Expires: "0",
    },
  });
};
