/**
 * Supabase Database Types
 * This file will be auto-generated by `pnpm db:generate`
 * For now, we define the expected schema manually
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          plan: string;
          settings: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          plan?: string;
          settings?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          plan?: string;
          settings?: Json;
          updated_at?: string;
        };
      };
      users: {
        Row: {
          id: string;
          organization_id: string | null;
          role: string;
          profile: Json;
          created_at: string;
        };
        Insert: {
          id: string;
          organization_id?: string | null;
          role?: string;
          profile?: Json;
          created_at?: string;
        };
        Update: {
          organization_id?: string | null;
          role?: string;
          profile?: Json;
        };
      };
      agents: {
        Row: {
          id: string;
          organization_id: string;
          name: string;
          description: string | null;
          avatar: string | null;
          persona: Json;
          knowledge_graph_id: string | null;
          channels: Json;
          status: string;
          config: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          name: string;
          description?: string | null;
          avatar?: string | null;
          persona?: Json;
          knowledge_graph_id?: string | null;
          channels?: Json;
          status?: string;
          config?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          description?: string | null;
          avatar?: string | null;
          persona?: Json;
          knowledge_graph_id?: string | null;
          channels?: Json;
          status?: string;
          config?: Json;
          updated_at?: string;
        };
      };
      knowledge_graphs: {
        Row: {
          id: string;
          organization_id: string;
          agent_id: string | null;
          name: string;
          graph: Json;
          source: string | null;
          meta: Json | null;
          version: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          agent_id?: string | null;
          name: string;
          graph: Json;
          source?: string | null;
          meta?: Json | null;
          version?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          agent_id?: string | null;
          name?: string;
          graph?: Json;
          source?: string | null;
          meta?: Json | null;
          version?: number;
          updated_at?: string;
        };
      };
      conversations: {
        Row: {
          id: string;
          organization_id: string;
          agent_id: string;
          channel: string;
          external_id: string | null;
          customer: Json;
          messages: Json;
          metadata: Json;
          status: string;
          started_at: string;
          ended_at: string | null;
        };
        Insert: {
          id?: string;
          organization_id: string;
          agent_id: string;
          channel: string;
          external_id?: string | null;
          customer?: Json;
          messages?: Json;
          metadata?: Json;
          status?: string;
          started_at?: string;
          ended_at?: string | null;
        };
        Update: {
          channel?: string;
          external_id?: string | null;
          customer?: Json;
          messages?: Json;
          metadata?: Json;
          status?: string;
          ended_at?: string | null;
        };
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}

